CREATE TABLE commerce_report_history (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    month INT,
    year INT,
    commerce_document VARCHAR(255),
    commerce_names VARCHAR(255),
    commerce_type VARCHAR(255),
    department VARCHAR(255),
    province VARCHAR(255),
    district VARCHAR(255),
    manager_id INT,
    manager_document VARCHAR(255),
    manager_names VARCHAR(255),
    q_visits INT,
    quota_pp INT,
    progress_pp DOUBLE,
    nc_pp DOUBLE,
    ur DOUBLE,
    proy_pp INT,
    cumpl_pp VARCHAR(255),
    quota_ss INT,
    progress_ss DOUBLE,
    nc_ss DOUBLE,
    proy_ss INT,
    cumpl_ss VARCHAR(255),
    current_level_month VARCHAR(255),
    previous_level_month VARCHAR(255),
    improved VARCHAR(255),
    projected_level VARCHAR(255),
    progress_pp_previous_month DOUBLE,
    progress_pp_current_month DOUBLE,
    var VARCHAR(255),
    brand_campaign VARCHAR(255)
);
