-- daily_sales_details
CREATE TABLE IF NOT EXISTS `daily_sales_details` (
     `id` char(36) NOT NULL,
    `leader` varchar(36) DEFAULT NULL,
    `type` varchar(50) DEFAULT NULL,
    `login` varchar(36) DEFAULT NULL,
    `name` varchar(255) DEFAULT NULL,
    `day` tinyint DEFAULT NULL,
    `sum_pp` tinyint DEFAULT NULL,
    `sum_vr_pp` tinyint DEFAULT NULL,
    `sum_pp5_vr` tinyint DEFAULT NULL,
    `sum_pp_flex_vr` tinyint DEFAULT NULL,
    `porta_pp` tinyint DEFAULT NULL,
    `sum_pp5_porta` tinyint DEFAULT NULL,
    `sum_pp_flex_porta` tinyint DEFAULT NULL,
    `ur_s` tinyint DEFAULT NULL,
    `non_commissionables_pp` tinyint DEFAULT NULL,
    `sum_nc_vr_pp` tinyint DEFAULT NULL,
    `sum_pp5_vr_nc` tinyint DEFAULT NULL,
    `sum_nc_pp_flex_vr` tinyint DEFAULT NULL,
    `non_commissionables_porta_pp` tinyint DEFAULT NULL,
    `sum_nc_porta_pp5` tinyint DEFAULT NULL,
    `sum_nc_pp_flex_porta` tinyint DEFAULT NULL,
    `sum_ss` tinyint DEFAULT NULL,
    `sum_ss_vr` tinyint DEFAULT NULL,
    `sum_oss` tinyint DEFAULT NULL,
    `sum_porta_90_ss_oss` tinyint DEFAULT NULL,
    `sum_opp` tinyint DEFAULT NULL,
    `sum_porta_90_ss_opp` tinyint DEFAULT NULL,
    `sum_llaa` tinyint DEFAULT NULL,
    `sum_nc_ss` tinyint DEFAULT NULL,
    `sum_nc_ss_vr` tinyint DEFAULT NULL,
    `sum_nc_oss` tinyint DEFAULT NULL,
    `sum_porta_90_nc_ss_oss` tinyint DEFAULT NULL,
    `sum_nc_opp` tinyint DEFAULT NULL,
    `sum_porta_90_nc_ss_opp` tinyint DEFAULT NULL,
    `sum_nc_llaa` tinyint DEFAULT NULL,
    `daily_sales_information_id` char(36) NOT NULL,
    `manager_id` char(36) DEFAULT NULL,
    `commerce_id` char(36) DEFAULT NULL,
    `seller_id` char(36) DEFAULT NULL,
    `has_error` tinyint DEFAULT '0',
    `error_description` varchar(255) DEFAULT NULL,
    `active` tinyint DEFAULT '1',
    PRIMARY KEY (`id`),
    KEY `fk_daily_sales_detail_information_idx` (`daily_sales_information_id`),
    KEY `fk_daily_sales_detail_pos_actors_idx` (`manager_id`),
    KEY `fk_daily_sales_detail_commerce_actors_idx` (`commerce_id`),
    KEY `fk_daily_sales_detail_seller_actor_id_idx` (`seller_id`),
    CONSTRAINT `fk_daily_sales_detail_commerce_actor_id` FOREIGN KEY (`commerce_id`) REFERENCES `actors` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_daily_sales_detail_information` FOREIGN KEY (`daily_sales_information_id`) REFERENCES `daily_sales_informations` (`id`),
    CONSTRAINT `fk_daily_sales_detail_manager_actor_id` FOREIGN KEY (`manager_id`) REFERENCES `actors` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT `fk_daily_sales_detail_seller_actor_id` FOREIGN KEY (`seller_id`) REFERENCES `actors` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;